c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

sysroot_version:
  - "2.17"

cmake_version:
  - ">=3.26.4"

proj_version:
  - ">=9.2.0,<10a0"
